---
title: "jornada_analysis"
author: "Hannah Dempsey"
output: github_document
---

# Jornada Basin Analysis

Set up:

```{r}
library(tidyverse)
jornada_clean <- read_csv("../data_clean/jornada_clean.csv")
```

### Abundance Data

Calculate the annual abundance for each species per trapnight:

```{r}
rodents_per_trapnight <- jornada_clean %>% 
  group_by(year, species) %>%
  summarize(abundance = n()) %>% 
  #from metadata: 3 nights with 144 traps
  mutate(trap_nights = 3 * 144,
         abund_per_trapnight = abundance / trap_nights)

#save dataframe for comparison
write_csv(rodents_per_trapnight, "../data_clean/jornada_abund_trapnights.csv")
```

Plotting abundance per trapnight:

```{r}
rodents_per_trapnight %>% 
  filter(!is.na(species)) %>% 
  ggplot(., aes(x = year, y = abund_per_trapnight)) +
  geom_point() +
  geom_line() +
  facet_wrap(~ species) +
  labs(y = "Rodent Abundance per Trapnight", x = "Year", title = "Jornada Basin") +
  theme_bw()

#DO THE GGSAVE
```

### Biomass Data

Calculating average mass for each species:

```{r}
rodent_mass <- jornada_clean %>% 
  group_by(species) %>% 
  summarize(avg_mass_g = mean(weight_g, na.rm = T))
rodent_mass
```

Calculate annual biomass of each species:

```{r}
biomass_annual <- rodents_per_trapnight %>% 
  inner_join(rodent_mass, join_by(species)) %>% 
  group_by(year, species) %>% 
  summarize(biomass_g = abund_per_trapnight * avg_mass_g)
biomass_annual

#save dataframe for comparison
write_csv(biomass_annual, "../data_clean/jornada_biomass.csv")
```

Plotting annual biomass of each species:

```{r}
biomass_annual %>% 
  filter(!is.na(species)) %>% 
  ggplot(., aes(x = year, y = biomass_g)) +
  geom_point() +
  geom_line() +
  facet_wrap(~species) +
  labs(y = "Biomass (g)", x = "Year", title = "Jornada Basin") +
  theme_bw()

#DO THE GGSAVE
```

Calculating annual community biomass:

```{r}
total_biomass_annual <- biomass_annual %>% 
  group_by(year) %>% 
  summarize(biomass_g = sum(biomass_g))
total_biomass_annual

#save dataframe for comparison
write_csv(total_biomass_annual, "../data_clean/jornada_total_biomass.csv")
```

Plotting annual community biomass:

```{r}
ggplot(total_biomass_annual, aes(x = year, y = biomass_g)) +
  geom_point() +
  geom_line() +
  labs(y = "Total Biomass (g)", x = "Year", title = "Jornada Basin") +
  theme_bw()
```
