---
title: "portal_analysis"
author: "Hannah Dempsey"
output: github_document
---

# Portal Analysis

Set up:

```{r}
library(tidyverse)
library(portalr)

#loading in portal data using portalr package
portal <- abundance(effort = T, level = "Treatment", type = "Rodents", shape = "Flat")

#limit to control treatments
portal <- portal %>% 
  filter(treatment == "control")

data_tables <- load_rodent_data()
species <- data_tables$species_table
trapping <- data_tables$trapping_table
plots <- data_tables$plots_table
```

Cleaning data:

```{r}
#adding species information
portal <- portal %>% 
  left_join(species, join_by(species)) %>% 
  mutate(effort = ntraps / nplots,
         abund_per_trapnight = abundance / effort) %>% 
  select(1:9, 21:22) %>% 
  rename(scientific_name = scientificname,
         common_name = commonname)
portal

#adding period dates
period_durations <- trapping %>% 
  mutate(date = make_date(year = year,
                         month = month,
                         day = day)) %>% 
  select(4:9) %>% 
  group_by(period) %>% 
  summarize(start_date = min(date),
            end_date = max(date))
period_durations

portal <- portal %>% 
  left_join(period_durations, join_by(period)) %>% 
  mutate(year = year(end_date),
         month = month(end_date)) %>% 
  select(14, 15, everything())
portal
```

### Abundance Data

Plotting abundance per trapnight for each period:

```{r}
portal %>% 
  filter(abund_per_trapnight != 0) %>% 
  ggplot(., aes(x = start_date, y = abund_per_trapnight)) +
  geom_point() +
  geom_line() +
  facet_wrap(~species) +
  labs(x = "Year", y = "Rodent Abundance per Trapnight", title = "Portal Project") +
  theme_bw()
```

Plotting abundance by year: REPLACE PERIOD WITH THIS GRAPH?

```{r}
portal %>% 
  group_by(year, species) %>% 
  summarize(abundance = sum(abundance),
            effort = sum(effort)) %>% 
  mutate(abund_per_trapnight = abundance / effort) %>% 
  ggplot(., aes(x = year, y = abund_per_trapnight)) +
  geom_point() +
  geom_line() +
  facet_wrap(~species) +
  labs(x = "Year", y = "Rodent Abundance per Trapnight", title = "Portal Project") +
  theme_bw()
```

### Biomass Data

Adding average mass for each species:

```{r}
portal <- species %>% 
  select(1, 13) %>% 
  right_join(portal, join_by(species)) %>% 
  rename(avg_mass_g = meanwgt)
portal
```

Calculate the biomass of each species:

```{r}
biomass <- portal %>% 
  group_by(year, month, species) %>% 
  summarize(biomass_g = abund_per_trapnight * avg_mass_g) %>%
  unite(date, year:month, sep = "-") %>% 
  mutate(date = ym(date))
biomass
```

Plotting biomass of each species

```{r}
biomass %>% 
  filter(biomass_g != 0) %>% 
ggplot(., aes(x = date, y = biomass_g)) +
  geom_point() +
  geom_line() +
  facet_wrap(~species, ncol = 3) +
  labs(y = "Biomass (g)", x = "Year", title = "Portal Project") +
  theme_bw()
```

Calculating community biomass

```{r}
total_biomass <- biomass %>% 
  group_by(date) %>% 
  summarize(biomass_g = sum(biomass_g))
total_biomass
```

Plotting community biomass

```{r}
ggplot(total_biomass, aes(x = date, y = biomass_g)) +
  geom_point() +
  geom_line() +
  labs(y = "Biomass (g)", x = "Year", title = "Portal Project") +
  theme_bw()
```
